### ISSUE TITLE
mmCIF <-> PDB utility

### ISSUE THREAD

**Issue by amjjbonvin** [JoaoRodrigues/pdb-tools#27]
It would be nice to have a simple way of converting a mmCIF file into the regular PDB file (and ideally the other way around too - but this might be more complicated)

**Comment by JoaoRodrigues** [comment]
This is something I've given a lot of thought to. My biggest concern is the only structures that do not have a PDB file available are those with too many residues or atoms or chains. If we had an internal representation for the data, sure, no biggie in parsing, manipulating everything, and then writing it in the right format. But we don't, sort of on purpose. Then there's the concern that the mmCIF format packs much more information, and that this information cross-references other parts of the file. So either we'd stick to dealing with coordinates and strip the mmCIF of most of the information, which is a bit of a waste, or we'd have to write a proper mmCIF parser. 

What I can do is to have a one-way converter from mmCIF to PDB, with the caveat that it will fail if the structure is too large. This allows files in cif format to be manipulated as long as they are small enough and since we are losing information anyway with the PDB format. What do you think?

**Comment by amjjbonvin** [comment]
Probably a mmCIF to PDB utility would be nice. Not sure how long will the PDB keep providing the old PDB format... Can of course be done with other software like PyMol

**Comment by mtrellet** [comment]
We have such a converter in HADDOCK2.4 web server, this actually based on the [FastMMCIFParser](http://biopython.org/DIST/docs/api/Bio.PDB.MMCIFParser%27-pysrc.html#FastMMCIFParser.__init__) provided by biopython. Which also "supports" ihm_mmcif in the sense that it does not complain when he does not know some categories.
But this does not align well with the idea of not relying on external libraries... And I'm not sure about the behavior when there are too many atoms. Something to test.

**Comment by JoaoRodrigues** [comment]
My suggestion is to provide a simple converter that picks the _atom_site
entries of an mmCIF file and dumps ATOM/HETATM lines. If the file has over
9999 residues in a single chain or more than 99999 atoms, then it throws an
exception and quits. We already do some of these checks when renumbering
atoms/residues.

About FastMMCIFParser: I wrote that one, it basically parses the _atom_site
entries of the mmCIF file into a bunch of dictionaries, that's why it
probably never complains :)

**Comment by mtrellet** [comment]
Agree with the principle, just fetch the _atom_site and do some basic checks ;)

Was not completely sure it was you, good job!

**Comment by JoaoRodrigues** [comment]
Addressed by 35674d3. Can you check it produces decent things? It passed some of my tests, including going from a PDB to mmCIF and back to PDB.

**Comment by JoaoRodrigues** [comment]
Added tools, manually verified with PyMOL and OpenMM mmCIF files. Seems to work ... Added test suite as well.
